# Full credit goes to https://github.com/conda/conda-recipes for providing this recipe.
# It has been subsequently adapted for automated building with conda-forge and matplotlib.

package:
  name: matplotlib
  version: {{ load_setup_py_data().version }}

source:
  path: ../../

requirements:
  build:
    - python
    - setuptools
    - pkg-config  # [not win]
    - numpy x.x
    - python-dateutil
    - freetype 2.6*
    - msinttypes  # [win]
    - cycler >=0.10
    - pytest >=3.0.0
    - pyparsing
    - pytz
#    - py2cairo  # [linux and py2k]
    - tornado
    - libpng >=1.6.21,<1.7
    - zlib 1.2*  # [win]
    - pyqt 4*  # [not osx]
    - tk 8.5*  # [linux]
    - backports.functools_lru_cache  # [py2k]

  run:
    - python
    - numpy x.x
    - cycler >=0.10
    - python-dateutil
    - freetype 2.6*
    - pytz
    - pyparsing
#    - py2cairo  # [linux and py2k]
    - qt 4*
    - libpng >=1.6.21,<1.7
    - pyqt 4*  # [not osx]
    - tk 8.5*  # [linux and win]
    - backports.functools_lru_cache  # [py2k]

test:
    imports:
        - matplotlib
        - matplotlib.pyplot

about:
  home: http://matplotlib.org/
  license: PSF-based (http://matplotlib.org/users/license.html)
  summary: Publication quality figures in Python

extra:
  recipe-maintainers:
    - janschulz # only in the mpl repository
    - mdboom # rest form conda-forge
    - ocefpaf
    - pelson
    - tacaswell
